In [243]:
import numpy as np

# Hello heading

In [244]:
my_data = np.genfromtxt('data.csv', delimiter=',',dtype=str)

In [245]:
my_data

array([['Index', 'Outlook', 'Temperature', 'Humidty', 'Windy', 'PlayGolf'],
       ['0', '0', '0', '1', '0', '0'],
       ['1', '0', '0', '1', '1', '0'],
       ['2', '1', '0', '1', '0', '1'],
       ['3', '2', '1', '1', '0', '1'],
       ['4', '2', '2', '0', '0', '1'],
       ['5', '2', '2', '0', '1', '0'],
       ['6', '1', '2', '0', '1', '1'],
       ['7', '0', '1', '1', '0', '0'],
       ['8', '0', '2', '0', '0', '1'],
       ['9', '2', '1', '0', '0', '1'],
       ['10', '0', '1', '1', '1', '1'],
       ['11', '1', '1', '1', '1', '1'],
       ['12', '1', '0', '0', '0', '1'],
       ['13', '2', '1', '1', '1', '0']],
      dtype='|S11')

In [246]:
columns = my_data[0:1]
print columns

[['Index' 'Outlook' 'Temperature' 'Humidty' 'Windy' 'PlayGolf']]


In [247]:
#my_data = my_data[1:]

In [248]:
my_data

array([['Index', 'Outlook', 'Temperature', 'Humidty', 'Windy', 'PlayGolf'],
       ['0', '0', '0', '1', '0', '0'],
       ['1', '0', '0', '1', '1', '0'],
       ['2', '1', '0', '1', '0', '1'],
       ['3', '2', '1', '1', '0', '1'],
       ['4', '2', '2', '0', '0', '1'],
       ['5', '2', '2', '0', '1', '0'],
       ['6', '1', '2', '0', '1', '1'],
       ['7', '0', '1', '1', '0', '0'],
       ['8', '0', '2', '0', '0', '1'],
       ['9', '2', '1', '0', '0', '1'],
       ['10', '0', '1', '1', '1', '1'],
       ['11', '1', '1', '1', '1', '1'],
       ['12', '1', '0', '0', '0', '1'],
       ['13', '2', '1', '1', '1', '0']],
      dtype='|S11')

In [249]:
total_samples = len(my_data)
print total_samples

label_columns = my_data[:,-1]
label_columns

15


array(['PlayGolf', '0', '0', '1', '1', '1', '0', '1', '0', '1', '1', '1',
       '1', '1', '0'],
      dtype='|S11')

In [261]:

def calulate_prior(full_data):
    columns = full_data[0:1][0]
    full_data = full_data[1:].astype(int)
    label_columns = full_data[:,-1]
    print label_columns
    print 
    n_samples_yes = len(label_columns[label_columns==1])
    n_samples_no = len(label_columns[label_columns==0])
    print "n_samples_yes",n_samples_yes
    #print full_data
    print len(columns)
    print columns
    col_id = 1
    prob_dict = {}
    prob_dict[1]= ((n_samples_yes)*1.0)/len(full_data)
    prob_dict[0]= ((n_samples_no)*1.0)/len(full_data)
    for col_name in columns[1:-1]:
        print "col id is",col_id, col_name
        
        temp_data = np.dstack([full_data[:,col_id],label_columns[:]])[0]
        print temp_data
        prob_dict[col_name]= {}
        for unique_feature in np.unique(full_data[:,col_id]):
            print "unique f",unique_feature,['Rainy','overcast','sunny'][unique_feature]
            prob_dict[col_name][unique_feature] = {}
            print unique_feature
            get_rows = temp_data[temp_data[:,0]==unique_feature]
            get_rows = get_rows.astype(int)
            print get_rows
            #class_1 = str((len(get_rows[np.where(get_rows[:,1] == 1)])*1.0))+'//'+str(n_samples_yes)
            class_1 = (len(get_rows[np.where(get_rows[:,1] == 1)])*1.0)/n_samples_yes
            print class_1
            #class_0 = str(len(get_rows[np.where(get_rows[:,1] == 0)])*1.0)+'//'+str(n_samples_no)
            class_0 = (len(get_rows[np.where(get_rows[:,1] == 0)])*1.0)/n_samples_no
            print class_0
            prob_dict[col_name][unique_feature][0] = class_0
            prob_dict[col_name][unique_feature][1] = class_1
        col_id+=1
        
    return prob_dict


In [262]:
prior_dict = calulate_prior(my_data)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]

n_samples_yes 9
6
['Index' 'Outlook' 'Temperature' 'Humidty' 'Windy' 'PlayGolf']
col id is 1 Outlook
[[0 0]
 [0 0]
 [1 1]
 [2 1]
 [2 1]
 [2 0]
 [1 1]
 [0 0]
 [0 1]
 [2 1]
 [0 1]
 [1 1]
 [1 1]
 [2 0]]
unique f 0 Rainy
0
[[0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]]
0.222222222222
0.6
unique f 1 overcast
1
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
0.444444444444
0.0
unique f 2 sunny
2
[[2 1]
 [2 1]
 [2 0]
 [2 1]
 [2 0]]
0.333333333333
0.4
col id is 2 Temperature
[[0 0]
 [0 0]
 [0 1]
 [1 1]
 [2 1]
 [2 0]
 [2 1]
 [1 0]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]]
unique f 0 Rainy
0
[[0 0]
 [0 0]
 [0 1]
 [0 1]]
0.222222222222
0.4
unique f 1 overcast
1
[[1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]]
0.444444444444
0.4
unique f 2 sunny
2
[[2 1]
 [2 0]
 [2 1]
 [2 1]]
0.333333333333
0.2
col id is 3 Humidty
[[1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]]
unique f 0 Rainy
0
[[0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
0.555555555556
0.2
unique f 1

In [263]:
sample_input = [0,0,0,0]
print prior_dict
print prior_dict.keys()

{0: 0.35714285714285715, 1: 0.6428571428571429, 'Outlook': {0: {0: 0.6, 1: 0.2222222222222222}, 1: {0: 0.0, 1: 0.4444444444444444}, 2: {0: 0.4, 1: 0.3333333333333333}}, 'Temperature': {0: {0: 0.4, 1: 0.2222222222222222}, 1: {0: 0.4, 1: 0.4444444444444444}, 2: {0: 0.2, 1: 0.3333333333333333}}, 'Windy': {0: {0: 0.4, 1: 0.6666666666666666}, 1: {0: 0.6, 1: 0.3333333333333333}}, 'Humidty': {0: {0: 0.2, 1: 0.5555555555555556}, 1: {0: 0.8, 1: 0.4444444444444444}}}
[0, 1, 'Outlook', 'Temperature', 'Windy', 'Humidty']


In [270]:
def predict(sample_input,prior_dict=prior_dict):
    yes_prob = 1.0
    no_prob = 1.0
    for f_id,feature_names in enumerate(prior_dict.keys()[2:]):
        yes_prob *= prior_dict[feature_names][sample_input[f_id]][1]
        no_prob *= prior_dict[feature_names][sample_input[f_id]][0]
    
    yes_prob *=prior_dict[1]
    no_prob *=prior_dict[0]
    
    if yes_prob>no_prob:
        print "Play Golf"
    else:
        print "Dont play Golf"
    return yes_prob>no_prob
predict(sample_input)

Play Golf


True

In [264]:
yes_prob = 1.0
no_prob = 1.0
for f_id,feature_names in enumerate(prior_dict.keys()[2:]):
    
    print prior_dict[feature_names]
    print feature_names,sample_input[f_id], prior_dict[feature_names][sample_input[f_id]][0]
    yes_prob *= prior_dict[feature_names][sample_input[f_id]][1]
    no_prob *= prior_dict[feature_names][sample_input[f_id]][0]

{0: {0: 0.6, 1: 0.2222222222222222}, 1: {0: 0.0, 1: 0.4444444444444444}, 2: {0: 0.4, 1: 0.3333333333333333}}
Outlook 0 0.6
{0: {0: 0.4, 1: 0.2222222222222222}, 1: {0: 0.4, 1: 0.4444444444444444}, 2: {0: 0.2, 1: 0.3333333333333333}}
Temperature 0 0.4
{0: {0: 0.4, 1: 0.6666666666666666}, 1: {0: 0.6, 1: 0.3333333333333333}}
Windy 0 0.4
{0: {0: 0.2, 1: 0.5555555555555556}, 1: {0: 0.8, 1: 0.4444444444444444}}
Humidty 0 0.2


In [268]:
#final_yes = (yes_prob)/(yes_prob+no_prob)
yes_prob *=prior_dict[1]
no_prob *=prior_dict[0]

In [269]:
if yes_prob>no_prob:
    print "Play Golf"
else:
    print "Dont play Golf"

Play Golf


In [267]:
no_prob*prior_dict[0]

0.006857142857142858