In [1]:
from fromscratchtoml.decomposition import Decomposition
from fromscratchtoml.toolbox import binary_visualize

from sklearn.decomposition import PCA
import numpy as np
%matplotlib inline

In [2]:
n = 5
n_dim = 3
nc = 3

X = np.zeros([n, n_dim])
if n_dim==3:
    m = 5
    c = 2
    d = 5
    for i in range(n):
        X[i,0] = i
        X[i,1] = m*i + c
#         X[i,1] = np.sqrt(i)
        X[i,2] = (d - 2*X[i,0] - 3*X[i,1])/2

elif n_dim==2:
    for i in range(n):
        X[i,0] = i
        X[i,1] = 2*i

print(X)
print(X[0])

[[  0.    2.   -0.5]
 [  1.    7.   -9. ]
 [  2.   12.  -17.5]
 [  3.   17.  -26. ]
 [  4.   22.  -34.5]]
[ 0.   2.  -0.5]


In [3]:
# X = np.zeros([4, 2])
# X[0,0] = 2
# X[0,1] = 4
# X[1,0] = 1
# X[1,1] = 3
# X[2,0] = 0
# X[2,1] = 0
# X[3,0] = 0
# X[3,1] = 0

# X = ch.zeros([2, 2])
# X[0,0] = 4
# X[0,1] = 0
# X[1,0] = 3
# X[1,1] = -5

# X = np.zeros([2, 3])
# X[0,0] = 2
# X[0,1] = -2
# X[0,2] = 1
# X[1,0] = 5
# X[1,1] = 1
# X[1,2] = 4

In [4]:
r_x, evals, evecs = Decomposition.pca(X - X.mean(0))

In [5]:
# binary_visualize(X)

In [6]:
# binary_visualize(ch.stack((r_x[...,0], r_x[...,1]), 1))

In [7]:
# binary_visualize(ch.stack((r_x[...,0], r_x[...,2]), 1))

In [8]:
# binary_visualize(ch.stack((r_x[...,1], r_x[...,2]), 1))

In [9]:
# X = X.numpy()

In [10]:
pca = PCA(n_components=X.shape[1])
pca.fit(X)
skl_x = pca.transform(X)
print(skl_x)

[[ 1.98242276e+01  3.66373598e-15 -4.55191440e-15]
 [ 9.91211380e+00  1.83186799e-15 -2.27595720e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.91211380e+00 -1.83186799e-15  2.27595720e-15]
 [-1.98242276e+01 -3.66373598e-15  4.55191440e-15]]


In [11]:
r_x

array([[  6.81298774, -18.55212225,   1.54982524],
       [  3.40649387,  -9.27606112,   0.77491262],
       [  0.        ,   0.        ,   0.        ],
       [ -3.40649387,   9.27606112,  -0.77491262],
       [ -6.81298774,  18.55212225,  -1.54982524]])

In [12]:
skl_reconstructed_x = np.dot(skl_x, pca.components_) + X.mean(axis=0)
reconstructed_x = np.dot(r_x, evecs) + X.mean(axis=0)
print(skl_reconstructed_x)
print("")
print(reconstructed_x)

[[-4.4408921e-16  2.0000000e+00 -5.0000000e-01]
 [ 1.0000000e+00  7.0000000e+00 -9.0000000e+00]
 [ 2.0000000e+00  1.2000000e+01 -1.7500000e+01]
 [ 3.0000000e+00  1.7000000e+01 -2.6000000e+01]
 [ 4.0000000e+00  2.2000000e+01 -3.4500000e+01]]

[[  6.60769734   4.48995107   0.25861172]
 [  4.30384867   8.24497553  -8.62069414]
 [  2.          12.         -17.5       ]
 [ -0.30384867  15.75502447 -26.37930586]
 [ -2.60769734  19.51004893 -35.25861172]]


In [13]:
X

array([[  0. ,   2. ,  -0.5],
       [  1. ,   7. ,  -9. ],
       [  2. ,  12. , -17.5],
       [  3. ,  17. , -26. ],
       [  4. ,  22. , -34.5]])

In [14]:
evecs.T

array([[ 0.82430398,  0.10088665,  0.55708601],
       [ 0.44025326,  0.50443327, -0.74278135],
       [ 0.35594945, -0.85753656, -0.37139068]])

In [15]:
pca.components_

array([[-0.10088665, -0.50443327,  0.85753656],
       [-0.82430398, -0.44025326, -0.35594945],
       [-0.55708601,  0.74278135,  0.37139068]])

In [16]:
print(X)

[[  0.    2.   -0.5]
 [  1.    7.   -9. ]
 [  2.   12.  -17.5]
 [  3.   17.  -26. ]
 [  4.   22.  -34.5]]
