In [1]:
from fromscratchtoml.neural_network.models import Sequential
from fromscratchtoml.neural_network.optimizers import StochasticGradientDescent
from fromscratchtoml.neural_network.layers import Dense, Activation

import numpy as np
from sklearn.model_selection import train_test_split


# Neural Networks

In [71]:
model = Sequential()
model.add(Dense(5, input_dim=2))
model.add(Activation('sigmoid'))
model.add(Dense(2))
model.add(Activation('sigmoid'))
sgd = StochasticGradientDescent(learning_rate=2.5)
model.compile(optimizer=sgd, loss="mean_squared_error")

In [72]:
X = np.array([[0, 0],[0, 1],[1, 0], [1, 1]])
y = np.array([[1,0], [0,1], [0,1], [1,0]])

In [73]:
model.fit(X, y, batch_size=4, epochs=100)

(0.0726934361297971, 'loss')
(0.1084290713597063, 'loss')
(0.13124627108127884, 'loss')
(0.1583544358634341, 'loss')
(0.20405794613883937, 'loss')
(0.24543645017592813, 'loss')
(0.2666698149938498, 'loss')
(0.27798091736383335, 'loss')
(0.2859612305185658, 'loss')
(0.293004589579553, 'loss')
(0.2997959426356315, 'loss')
(0.3064147049701571, 'loss')
(0.3127717096247719, 'loss')
(0.3187696810134965, 'loss')
(0.324348309380069, 'loss')
(0.32948597566273297, 'loss')
(0.3341893827571103, 'loss')
(0.33848267857576453, 'loss')
(0.3423991237395818, 'loss')
(0.34597529743363387, 'loss')
(0.3492470705748805, 'loss')
(0.3522465962605651, 'loss')
(0.35499977150467266, 'loss')
(0.35752381814800355, 'loss')
(0.35982477919350053, 'loss')
(0.3618948466909885, 'loss')
(0.3637095585004402, 'loss')
(0.36522505127654487, 'loss')
(0.3663757511774187, 'loss')
(0.36707311332150516, 'loss')
(0.3672062387818672, 'loss')
(0.3666453099127086, 'loss')
(0.3652486622530592, 'loss')
(0.3628738364691499, 'loss')
(0.3

In [74]:
model.predict(np.array([1,0]))

array([[0.09471975],
       [0.90831637]])

In [75]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original', data_home="/home/markroxor/Downloads")
X = mnist.data
y = mnist.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=10000, random_state=42)
X_train.shape, y_train.shape

((60000, 784), (60000,))

In [82]:
a = []
for i in range(len(y_train)):
    x = np.zeros(10)
    x[int(y_train[i])] = 1.
    a.append(np.expand_dims(x, 1))
a = np.array(a, dtype=np.float128)

In [83]:
# a = np.expand_dims(a, 0)
a[0]

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float128)

In [84]:
model = Sequential()
model.add(Dense(30, input_dim=784))
model.add(Activation('sigmoid'))
model.add(Dense(10))
model.add(Activation('sigmoid'))
sgd = StochasticGradientDescent(learning_rate=2)
model.compile(optimizer=sgd, loss="mean_squared_error")

In [85]:
model.fit(X_train, a, batch_size=10, epochs=1)

(0.09610663853530329155, 'loss')


In [92]:
model.predict(X_train[10])

array([[0.10292393],
       [0.0022676 ],
       [0.15766186],
       [0.02334977],
       [0.04417828],
       [0.03048914],
       [0.06455242],
       [0.05815137],
       [0.03087108],
       [0.07537097]], dtype=float128)

In [89]:
y_train[102]

4.0