In [1]:
from fromscratchtoml.neural_network.models import Sequential
from fromscratchtoml.neural_network.optimizers import StochasticGradientDescent
from fromscratchtoml.neural_network.layers import Dense, Activation

import numpy as np
from sklearn.model_selection import train_test_split


In [2]:
model = Sequential()
model.add(Dense(5, input_dim=2))
model.add(Activation('sigmoid'))
model.add(Dense(2))
model.add(Activation('sigmoid'))
model.compile(optimizer=StochasticGradientDescent(learning_rate=0.1), loss="mean_squared_error")

In [3]:
X = np.array([[0, 0],[0, 1],[1, 0], [1, 1]])
y = [[1,0], [0,1], [0,1], [1,0]]

In [4]:
model.fit(X, y, batch_size=4, epochs=1)

[0 0]
[[ 2.48202634  1.08129808  1.60494339  0.47274011  0.27206663]
 [ 0.58413933 -1.01449166 -1.43130733 -0.5234301   1.26680066]]
[0. 0. 0. 0. 0.]
[[ 0.89912807]
 [ 1.91455501]
 [ 0.17405151]
 [-0.03298063]
 [ 0.26143763]]


ValueError: too many values to unpack

In [ ]:
zz

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0, random_state=42)
X_train

In [ ]:
nw = NeuralNetwork([2, 5, 2])

In [ ]:
nw.SGD(train_data=np.array([X_train, y_train]), epochs=50, batch_size=4, lr=3, test_data=np.array([X_train, y_train]))

In [ ]:
train_loader =  datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ]))
test_loader = datasets.MNIST('../data', train=False, transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ]))

In [ ]:
type(train_loader)

In [ ]:
nw = NeuralNetwork([784, 30, 10])

In [ ]:
nw.SGD(train_data=train_loader, epochs=30, batch_size=10, lr=0.5, test_data=test_loader)