In [1]:
from fromscratchtoml.neural_network.models import Sequential
from fromscratchtoml.neural_network.optimizers import StochasticGradientDescent
from fromscratchtoml.neural_network.layers import Dense, Activation

import numpy as np
from sklearn.model_selection import train_test_split


# Neural Networks

## Fitting a XOR gate

In [2]:
# [:, np.newaxis]
model = Sequential()
model.add(Dense(5, input_dim=2))
model.add(Activation('sigmoid'))
model.add(Dense(2))
model.add(Activation('sigmoid'))
sgd = StochasticGradientDescent(learning_rate=2)
model.compile(optimizer=sgd, loss="mean_squared_error")

In [3]:
X = np.array([[0, 0],[0, 1],[1, 0], [1, 1]])
y = np.array([[1,0], [0,1], [0,1], [1,0]])
y

array([[1, 0],
       [0, 1],
       [0, 1],
       [1, 0]])

In [4]:
model.fit(X, y, batch_size=4, epochs=50)

[██                                                                                                  ] 2%
[████                                                                                                ] 4%
[██████                                                                                              ] 6%
[████████                                                                                            ] 8%
[██████████                                                                                          ] 10%
[████████████                                                                                        ] 12%
[██████████████                                                                                      ] 14%
[████████████████                                                                                    ] 16%
[██████████████████                                                                                  ] 18%
[████████████████████                    

In [5]:
model.predict(X) - y

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [-1.,  1.]])

In [6]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original', data_home=".")
X = mnist.data
y = mnist.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=10000, random_state=42)
X_train.shape, y_train.shape

((60000, 784), (60000,))

In [7]:
a = []
for i in range(len(y_train)):
    x = np.zeros(10)
    x[int(y_train[i])] = 1.
    a.append(np.expand_dims(x, 1))
#     a.append(x)
a = np.array(a, dtype=np.float128)
y_train[0], a.shape

(3.0, (60000, 10, 1))

In [8]:
# a = np.expand_dims(a, 0)
a[0]

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float128)

In [9]:
model = Sequential()
model.add(Dense(30, input_dim=784))
model.add(Activation('sigmoid'))
model.add(Dense(10))
model.add(Activation('sigmoid'))
sgd = StochasticGradientDescent(learning_rate=1)
model.compile(optimizer=sgd, loss="mean_squared_error")

In [10]:
model.fit(X_train, a, batch_size=10, epochs=1)

[████████████████████████████████████████████████████████████████████████████████████████████████████] 100%

epoch: 1/1 

/home/mark/.local/lib/python2.7/site-packages/fromscratchtoml-0.0.2-py2.7.egg/fromscratchtoml/neural_network/activations.py:49: RuntimeWarning: overflow encountered in exp
  _sigmoid = 1.0 / (1.0 + np.exp(-x))


In [11]:
model.forwardpass(X_train[1])

array([[0.10975118],
       [0.04900288],
       [0.15642538],
       [0.02542232],
       [0.00129357],
       [0.03228947],
       [0.0677715 ],
       [0.06215153],
       [0.03305179],
       [0.07800378]], dtype=float128)

In [12]:
y_train[100]

0.0