In [1]:
from fromscratchtoml.decomposition import Decomposition
from fromscratchtoml.toolbox import binary_visualize
import torch as ch

from sklearn.decomposition import PCA
import numpy as np
%matplotlib inline

In [2]:
n = 5
n_dim = 3

X = ch.zeros(n, n_dim)
if n_dim==3:
    m = 5
    c = 2
    d = 5
    for i in range(n):
        X[i,0] = i
        X[i,1] = m*i + c
#         X[i,1] = np.sqrt(i)
        X[i,2] = (d - 2*X[i,0] - 3*X[i,1])/2

elif n_dim==2:
    for i in range(n):
        X[i,0] = i
        X[i,1] = 2*i

print(X)


  0.0000   2.0000  -0.5000
  1.0000   7.0000  -9.0000
  2.0000  12.0000 -17.5000
  3.0000  17.0000 -26.0000
  4.0000  22.0000 -34.5000
[torch.FloatTensor of size 5x3]



In [3]:
# X = ch.zeros(4, 2)
# X[0,0] = 2
# X[0,1] = 4
# X[1,0] = 1
# X[1,1] = 3
# X[2,0] = 0
# X[2,1] = 0
# X[3,0] = 0
# X[3,1] = 0

# X = ch.zeros(2, 2)
# X[0,0] = 4
# X[0,1] = 0
# X[1,0] = 3
# X[1,1] = -5

# X = ch.zeros(2, 3)
# X[0,0] = 2
# X[0,1] = -2
# X[0,2] = 1
# X[1,0] = 5
# X[1,1] = 1
# X[1,2] = 4
n_comp = 3
A = X - X.mean(dim=0)
# print(type(A))
W = ch.mm(A, A.t())
# cov_matrix = Statistics.cov_matrix(W, W)

eigen_vals, eigen_vecs = np.linalg.eig(W)
U = eigen_vecs


Wt = ch.mm(A.t(), A)
# cov_matrixt = Statistics.cov_matrix(Wt, Wt)
eigen_valst, eigen_vecst = np.linalg.eig(Wt)
eigen_valst = sorted(eigen_valst, reverse=True)
V = eigen_vecst.T

# print(eigen_vals)
# print(eigen_valst)
# print(np.sqrt(eigen_vals))
# print(sorted(np.sqrt(eigen_valst), reverse=True))
# print("")

# print(U)
# print(np.sqrt(eigen_valst))
print(V,"V")

u, s, vh = np.linalg.svd(A.numpy(), full_matrices=True)
print("")
# print(u)
# print(s)
print(vh)

(array([[-0.9948979 ,  0.05115156, -0.08695766],
       [ 0.10088666,  0.5044333 , -0.85753655],
       [-0.05893861,  0.8634507 ,  0.50097823]], dtype=float32), 'V')

[[ 0.10088666  0.5044333  -0.85753655]
 [-0.05893861  0.8634507   0.50097823]
 [-0.9931506   0.         -0.11684125]]


In [4]:
print(ch.mm(X, ch.Tensor(V)))
print(ch.mm(X, ch.Tensor(vh)))


  0.2312   0.5771  -1.9656
  0.2418  -4.1889 -10.5985
  0.2523  -8.9549 -19.2315
  0.2628 -13.7209 -27.8644
  0.2733 -18.4869 -36.4974
[torch.FloatTensor of size 5x3]


  0.3787   1.7269   1.0604
  8.6267   6.5486   3.7009
 16.8746  11.3703   6.3414
 25.1226  16.1920   8.9819
 33.3706  21.0136  11.6224
[torch.FloatTensor of size 5x3]



In [5]:
print(X)


  0.0000   2.0000  -0.5000
  1.0000   7.0000  -9.0000
  2.0000  12.0000 -17.5000
  3.0000  17.0000 -26.0000
  4.0000  22.0000 -34.5000
[torch.FloatTensor of size 5x3]

