In [11]:
from fromscratchtoml.decomposition import Decomposition
from fromscratchtoml.toolbox import binary_visualize
import torch as ch

from sklearn.decomposition import PCA
import numpy as np
%matplotlib inline

In [12]:
n = 5
n_dim = 3

X = np.zeros([n, n_dim])

m = 5
c = 2
d = 5
for i in range(n):
    X[i,0] = i
    X[i,1] = m*i + c
#         X[i,1] = np.sqrt(i)
    X[i,2] = (d - 2*X[i,0] - 3*X[i,1])/2

print(X)

[[  0.    2.   -0.5]
 [  1.    7.   -9. ]
 [  2.   12.  -17.5]
 [  3.   17.  -26. ]
 [  4.   22.  -34.5]]


In [18]:
# X = np.zeros([4, 2])
# X[0,0] = 2
# X[0,1] = 4
# X[1,0] = 1
# X[1,1] = 3
# X[2,0] = 0
# X[2,1] = 0
# X[3,0] = 0
# X[3,1] = 0

# X = np.zeros([2, 2])
# X[0,0] = 4
# X[0,1] = 0
# X[1,0] = 3
# X[1,1] = -5

# X = np.zeros([2, 3])
# X[0,0] = 2
# X[0,1] = -2
# X[0,2] = 1
# X[1,0] = 5
# X[1,1] = 1
# X[1,2] = 4
n_comp = 3
A = X - X.mean(0)
# print(type(A))
W = np.dot(A, A.T)
# cov_matrix = Statistics.cov_matrix(W, W)

eigen_vals, eigen_vecs = np.linalg.eig(W)
U = eigen_vecs


Wt = np.dot(A.T, A)
# cov_matrixt = Statistics.cov_matrix(Wt, Wt)
eigen_valst, eigen_vecst = np.linalg.eig(Wt)
# eigen_valst = sorted(eigen_valst, reverse=True)
V = eigen_vecst.T

# print(eigen_vals)
# print(eigen_valst)
# print(np.sqrt(eigen_vals))
# print(sorted(np.sqrt(eigen_valst), reverse=True))
# print("")

print(U)
# print(np.sqrt(eigen_valst))
# print(V,"V")

u, s, vh = np.linalg.svd(A, full_matrices=True)
print("")
print(u)
# print(s)
# print(vh)

[[ 6.32455532e-01  1.52654118e-01 -8.75191559e-17  0.00000000e+00
   0.00000000e+00]
 [ 3.16227766e-01 -9.45852676e-01 -9.12870929e-01  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00]
 [-3.16227766e-01 -1.28108888e-01 -1.82574186e-01  8.94427191e-01
   0.00000000e+00]
 [-6.32455532e-01 -2.56217776e-01 -3.65148372e-01 -4.47213595e-01
   0.00000000e+00]]

[[-6.32455532e-01 -7.74596669e-01 -9.43043057e-17  4.53097430e-17
   0.00000000e+00]
 [-3.16227766e-01  2.58198890e-01 -9.12870929e-01  4.78638256e-17
   5.86301129e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.47213595e-01
  -8.94427191e-01]
 [ 3.16227766e-01 -2.58198890e-01 -1.82574186e-01  8.00000000e-01
  -4.00000000e-01]
 [ 6.32455532e-01 -5.16397779e-01 -3.65148372e-01 -4.00000000e-01
   2.00000000e-01]]


In [14]:
print(np.dot(X, ch.Tensor(V)))
print(np.dot(X, ch.Tensor(vh)))

[[ -1.92862191  -0.4869452   -0.54157367]
 [ -6.09994141  -8.32059668  -4.95564164]
 [-10.27126091 -16.15424816  -9.36970961]
 [-14.4425804  -23.98789964 -13.78377758]
 [-18.6138999  -31.82155112 -18.19784555]]
[[ -0.70088379   1.65759561   1.00555388]
 [ -9.72692434   5.0084471    3.36190487]
 [-18.75296488   8.35929858   5.71825587]
 [-27.77900543  11.71015007   8.07460687]
 [-36.80504598  15.06100156  10.43095786]]


In [5]:
print(X)

[[ 4.  0.]
 [ 3. -5.]]
